{{- range $secrets := .Values.secrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "es-{{ $secrets.targetName}}"
  namespace: "{{ .Values.namespace }}"
spec:
  refreshInterval: {{ .Values.refreshInterval }} # Cada cuánto tiempo sincronizar con Vault
  secretStoreRef:
    name: "{{ .Values.name }}-scrt-store"
    kind: SecretStore
  target:
    name: {{ $secrets.targetName }} # Este es el nombre final que usará tu App
    creationPolicy: Owner
  data:
    {{- range $var := $secrets.values }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ $secrets.vaultSecret }}
        property: .vaultKey
    {{- end }}
{{- end }}