apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: "{{ .Values.name }}-scrt-store"
  namespace: "{{ .Values.namespace }}"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          # El rol que creaste anteriormente en Vault
          role: "{{ .Values.vaultRoleName }}"
          mountPath: "kubernetes"
          serviceAccountRef:
            name: "{{ .Values.name }}-sa-to-secret"
            #audience: "https://kubernetes.default.svc.cluster.local"