apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: {{ .Values.name }}-sa-to-secret
  namespace: {{ .Values.namespace }}
secrets:
  - name: {{ .Values.name }}-secret